const STATUS_UI_ID = {
  assigned: "UI-PPH-0005",
  in_progress: "UI-PPH-0006",
  to_gate: "UI-PPH-0007",
  rejected: "UI-PPH-0008",
  done: "UI-PPH-0009",
};

const UI_TEXT = {
  ja: {
    "UI-PPH-0001": "ワークスペース",
    "UI-PPH-0002": "Guide Chat",
    "UI-PPH-0003": "Task Board",
    "UI-PPH-0004": "Event Log",
    "UI-PPH-0005": "割り当て済み",
    "UI-PPH-0006": "実行中",
    "UI-PPH-0007": "Gate待ち",
    "UI-PPH-0008": "差し戻し",
    "UI-PPH-0009": "完了",
    "UI-PPH-0010": "設定",
    "UI-PPH-0011": "Agent設定",
    "UI-PPH-0012": "Workspace設定",
    "UI-PPH-0201": "Sort: updated_at desc (固定)",
    "UI-PPH-0202": "Filter: none (MVP)",
    "UI-PPH-0203": "Limit: 50 (暫定)",
    "UI-PPH-0204": "Task Detail",
    "UI-PPH-0205": "Gate Panel",
    "UI-PPH-0206": "Reject Reason",
    "UI-PPH-0207": "Resident Preview Slot",
    "UI-PPH-0208": "3D Coming Soon",
    "UI-PPH-0209": "Reject",
    "UI-PPH-0210": "Approve",
    "UI-PPH-0211": "Agent / Guide",
    "UI-PPH-0212": "Agent / Gate",
    "UI-PPH-0213": "Agent / Resident",
    "UI-PPH-0214": "Safety",
    "UI-PPH-0215": "Workspace",
  },
  en: {
    "UI-PPH-0001": "Workspace",
    "UI-PPH-0002": "Guide Chat",
    "UI-PPH-0003": "Task Board",
    "UI-PPH-0004": "Event Log",
    "UI-PPH-0005": "Assigned",
    "UI-PPH-0006": "In Progress",
    "UI-PPH-0007": "Awaiting Gate",
    "UI-PPH-0008": "Rejected",
    "UI-PPH-0009": "Done",
    "UI-PPH-0010": "Settings",
    "UI-PPH-0011": "Agent",
    "UI-PPH-0012": "Workspace",
    "UI-PPH-0201": "Sort: updated_at desc (fixed)",
    "UI-PPH-0202": "Filter: none (MVP)",
    "UI-PPH-0203": "Limit: 50 (temporary)",
    "UI-PPH-0204": "Task Detail",
    "UI-PPH-0205": "Gate Panel",
    "UI-PPH-0206": "Reject Reason",
    "UI-PPH-0207": "Resident Preview Slot",
    "UI-PPH-0208": "3D Coming Soon",
    "UI-PPH-0209": "Reject",
    "UI-PPH-0210": "Approve",
    "UI-PPH-0211": "Agent / Guide",
    "UI-PPH-0212": "Agent / Gate",
    "UI-PPH-0213": "Agent / Resident",
    "UI-PPH-0214": "Safety",
    "UI-PPH-0215": "Workspace",
  },
};

const DYNAMIC_TEXT = {
  ja: {
    detail: "詳細",
    start: "開始",
    submit: "提出",
    gate: "Gate審査",
    resubmit: "再提出",
    selectedTask: "選択Task",
    description: "説明",
    constraints: "制約チェック",
    evidence: "Evidence",
    replay: "Replay",
    gateDecision: "Gate判定",
    gateReason: "判定理由",
    gateFixes: "修正項目",
    fixCondition: "修正条件",
    openGate: "Gate Panelを開く",
    close: "閉じる",
    noTaskSelected: "Taskを選択してください。",
    noTask: "Taskはまだありません。",
    noJob: "Cronはまだありません。",
    schedule: "実行間隔",
    instruction: "指示",
    lastRun: "最終実行",
    gateProfile: "Gate",
    gateReviewBy: "Gate審査",
    gateOnlyToGate: "現在の状態ではGate審査は実行できません。",
    rejectReasonPlaceholder: "差し戻し理由（最大3項目）",
    gateReasonTemplateLabel: "理由テンプレート",
    settingsReadonly: "MVP: 設定は閲覧のみ",
    view: "表示",
    guideHint: "Guideと会話しながらタスク化と進捗更新ができます。",
    guideInputPlaceholder: "Guideへメッセージを入力（Enterで送信 / Shift+Enterで改行）",
    guideSend: "送信",
    guideSending: "送信中",
    senderGuide: "guide",
    senderYou: "you",
    senderSystem: "system",
    errorToastTitle: "Error",
    errorToastClose: "close",
    eventSearchPlaceholder: "イベント検索（ID/概要/種別）",
    eventTypeAll: "種別: すべて",
    eventTypeDispatch: "種別: dispatch",
    eventTypeGate: "種別: gate",
    eventTypeTask: "種別: task",
    eventTypeJob: "種別: cron",
    eventTypeResubmit: "種別: resubmit",
    eventTypePlan: "種別: plan",
    pagePrev: "前へ",
    pageNext: "次へ",
    eventNoMatch: "条件に一致するイベントはありません。",
  },
  en: {
    detail: "Detail",
    start: "Start",
    submit: "Submit",
    gate: "Gate Review",
    resubmit: "Resubmit",
    selectedTask: "Selected Task",
    description: "Description",
    constraints: "Constraints Check",
    evidence: "Evidence",
    replay: "Replay",
    gateDecision: "Gate Decision",
    gateReason: "Reason",
    gateFixes: "Fixes",
    fixCondition: "Fix Condition",
    openGate: "Open Gate Panel",
    close: "Close",
    noTaskSelected: "Select a task first.",
    noTask: "No tasks yet.",
    noJob: "No cron jobs yet.",
    schedule: "Schedule",
    instruction: "Instruction",
    lastRun: "Last Run",
    gateProfile: "Gate",
    gateReviewBy: "Gate Review",
    gateOnlyToGate: "Gate review is only available for to_gate tasks.",
    rejectReasonPlaceholder: "Reject reasons (max 3)",
    gateReasonTemplateLabel: "Reason Templates",
    settingsReadonly: "MVP: read-only settings",
    view: "View",
    guideHint: "Talk with Guide to create tasks and update progress.",
    guideInputPlaceholder: "Message Guide (Enter to send / Shift+Enter for newline)",
    guideSend: "Send",
    guideSending: "Sending",
    senderGuide: "guide",
    senderYou: "you",
    senderSystem: "system",
    errorToastTitle: "Error",
    errorToastClose: "close",
    eventSearchPlaceholder: "Search events (id/summary/type)",
    eventTypeAll: "Type: all",
    eventTypeDispatch: "Type: dispatch",
    eventTypeGate: "Type: gate",
    eventTypeTask: "Type: task",
    eventTypeJob: "Type: cron",
    eventTypeResubmit: "Type: resubmit",
    eventTypePlan: "Type: plan",
    pagePrev: "Prev",
    pageNext: "Next",
    eventNoMatch: "No events match the current filter.",
  },
};

const MESSAGE_TEXT = {
  "MSG-PPH-0001": {
    ja: "Plan Cardを作成しました。",
    en: "Plan card created.",
  },
  "MSG-PPH-0002": {
    ja: "TaskをPalへ割り当てました。",
    en: "Tasks dispatched to resident.",
  },
  "MSG-PPH-0003": {
    ja: "Completion Ritualを保存してGateへ提出しました。",
    en: "Completion ritual saved and submitted to Gate.",
  },
  "MSG-PPH-0004": {
    ja: "Gate判定を記録しました。",
    en: "Gate decision recorded.",
  },
  "MSG-PPH-0005": {
    ja: "差し戻しTaskを再提出しました。",
    en: "Rejected task resubmitted.",
  },
  "MSG-PPH-0007": {
    ja: "Pal設定を適用しました。",
    en: "Resident constraints applied.",
  },
  "MSG-PPH-0008": {
    ja: "Plan完了を通知しました。",
    en: "Plan completion was posted.",
  },
  "MSG-PPH-0009": {
    ja: "Guideチャットを更新しました。",
    en: "Guide chat updated.",
  },
  "MSG-PPH-1001": {
    ja: "入力内容を確認してください。",
    en: "Check your input.",
  },
  "MSG-PPH-1002": {
    ja: "処理がタイムアウトしました。再試行してください。",
    en: "Operation timed out. Please retry.",
  },
  "MSG-PPH-1003": {
    ja: "保存に失敗しました。保存先を確認してください。",
    en: "Failed to save. Check storage destination.",
  },
  "MSG-PPH-1004": {
    ja: "対象データが見つかりません。",
    en: "Target data not found.",
  },
  "MSG-PPH-1005": {
    ja: "セーフティ制約により操作をブロックしました。",
    en: "Operation blocked by safety constraints.",
  },
  "MSG-PPH-1006": {
    ja: "現在の状態ではこの操作は実行できません。",
    en: "This action is not available in the current state.",
  },
  "MSG-PPH-1007": {
    ja: "Reject入力が上限を超えています。",
    en: "Reject input exceeds limit.",
  },
  "MSG-PPH-1008": {
    ja: "完了状態に不整合があります。状態を確認してください。",
    en: "Completion state is inconsistent. Check statuses.",
  },
  "MSG-PPH-1010": {
    ja: "Guide モデルが未設定です。Settings でモデルを設定してください。",
    en: "Guide model is not configured. Configure a model in Settings.",
  },
};

const GUIDE_MODEL_REQUEST_TIMEOUT_MS = 1600;
const GUIDE_SYSTEM_PROMPT = "Guide operating rules are not configured.";
